; Listing generated by Microsoft (R) Optimizing Compiler Version 19.40.33813.0 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

msvcjmc	SEGMENT
__D7DDF2D6_concurrencysal@h DB 01H
__9D2F2FE0_sal@h DB 01H
__65B97124_vadefs@h DB 01H
__E9DC9412_vcruntime@h DB 01H
__2F3F0443_intrin0@inl@h DB 01H
__8DD7F741_setjmp@h DB 01H
__4FCC7BC5_mmintrin@h DB 01H
__1B0272D9_corecrt@h DB 01H
__45DED006_corecrt_malloc@h DB 01H
__FA77ED4C_malloc@h DB 01H
__6909F846_xmmintrin@h DB 01H
__0C6B718A_emmintrin@h DB 01H
__D3CA1903_pmmintrin@h DB 01H
__63136A81_tmmintrin@h DB 01H
__4A287F02_smmintrin@h DB 01H
__2F4AF6CE_nmmintrin@h DB 01H
__FAF10C80_wmmintrin@h DB 01H
__31654187_zmmintrin@h DB 01H
__0671E34D_immintrin@h DB 01H
__BCB20208_ammintrin@h DB 01H
__ABE14B36_intrin@h DB 01H
__6A584D4A_iacaMarks@h DB 01H
__621B1B6F_triad@c DB 01H
msvcjmc	ENDS
PUBLIC	kernel
PUBLIC	__JustMyCode_Default
EXTRN	dummy:PROC
EXTRN	_RTC_InitBase:PROC
EXTRN	_RTC_Shutdown:PROC
EXTRN	__CheckForDebuggerJustMyCode:PROC
EXTRN	_fltused:DWORD
;	COMDAT pdata
pdata	SEGMENT
$pdata$kernel DD imagerel $LN9
	DD	imagerel $LN9+221
	DD	imagerel $unwind$kernel
pdata	ENDS
;	COMDAT rtc$TMZ
rtc$TMZ	SEGMENT
_RTC_Shutdown.rtc$TMZ DQ FLAT:_RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
_RTC_InitBase.rtc$IMZ DQ FLAT:_RTC_InitBase
rtc$IMZ	ENDS
;	COMDAT voltbl
voltbl	SEGMENT
_volmd	DB	06eH
	DB	0b7H
voltbl	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$kernel DD 025052301H
	DD	011e2323H
	DD	070170025H
	DD	05016H
xdata	ENDS
; Function compile flags: /Odt
;	COMDAT __JustMyCode_Default
_TEXT	SEGMENT
__JustMyCode_Default PROC				; COMDAT
	ret	0
__JustMyCode_Default ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT kernel
_TEXT	SEGMENT
r$1 = 4
i$2 = 36
a$ = 288
b$ = 296
c$ = 304
s$ = 312
repeat$ = 320
cur_elements$ = 328
kernel	PROC						; COMDAT
; File C:\Users\phl\Projects\GitHub\OSACA\validation\kernels\triad.c
; Line 18
$LN9:
	movsd	QWORD PTR [rsp+32], xmm3
	mov	QWORD PTR [rsp+24], r8
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	push	rbp
	push	rdi
	sub	rsp, 296				; 00000128H
	lea	rbp, QWORD PTR [rsp+32]
	lea	rcx, OFFSET FLAT:__621B1B6F_triad@c
	call	__CheckForDebuggerJustMyCode
	npad	1
; Line 19
	mov	DWORD PTR r$1[rbp], 0
	jmp	SHORT $LN4@kernel
$LN2@kernel:
	mov	eax, DWORD PTR r$1[rbp]
	inc	eax
	mov	DWORD PTR r$1[rbp], eax
$LN4@kernel:
	mov	eax, DWORD PTR repeat$[rbp]
	cmp	DWORD PTR r$1[rbp], eax
	jge	$LN3@kernel
; Line 20
	mov	DWORD PTR i$2[rbp], 0
	jmp	SHORT $LN7@kernel
$LN5@kernel:
	mov	eax, DWORD PTR i$2[rbp]
	inc	eax
	mov	DWORD PTR i$2[rbp], eax
$LN7@kernel:
	mov	eax, DWORD PTR cur_elements$[rbp]
	cmp	DWORD PTR i$2[rbp], eax
	jge	SHORT $LN6@kernel
; Line 21
	mov	al, 111					; 0000006fH
	mov	BYTE PTR gs:111, al
; Line 22
	movsxd	rax, DWORD PTR i$2[rbp]
	movsxd	rcx, DWORD PTR i$2[rbp]
	mov	rdx, QWORD PTR c$[rbp]
	movsd	xmm0, QWORD PTR s$[rbp]
	mulsd	xmm0, QWORD PTR [rdx+rcx*8]
	mov	rcx, QWORD PTR b$[rbp]
	movsd	xmm1, QWORD PTR [rcx+rax*8]
	addsd	xmm1, xmm0
	movaps	xmm0, xmm1
	movsxd	rax, DWORD PTR i$2[rbp]
	mov	rcx, QWORD PTR a$[rbp]
	movsd	QWORD PTR [rcx+rax*8], xmm0
; Line 23
	mov	al, 222					; 000000deH
	mov	BYTE PTR gs:222, al
; Line 24
	jmp	SHORT $LN5@kernel
$LN6@kernel:
; Line 25
	mov	rcx, QWORD PTR a$[rbp]
	call	dummy
	npad	1
; Line 26
	jmp	$LN2@kernel
$LN3@kernel:
; Line 27
	lea	rsp, QWORD PTR [rbp+264]
	pop	rdi
	pop	rbp
	ret	0
kernel	ENDP
_TEXT	ENDS
END
